### ISSUE TITLE
Complete badge components

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/min-ui#11]
# Complete badge components

Feature Aler component

## Epic Description

This feature will add a list of avatars and badge components on the docs page. Listed with the specific heading

## Badge tasks:

- [x] Task 1: Badge with avatars
- [x] Task 2: Badge with buttons
- [x] Task 3: Badge with icons
- [x] Added code snippets for all the components
