### ISSUE TITLE
Site enhancement

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/min-ui#13]
# Update docs styles and overall site

Task: Awesome Task Title

## Task Description

- [x]  This Task will update the layout of the site and add new styles. 
- [x] Updated navbar with blur effect
- [x] Add component display for showing component
- [x] Add code wrapper
