### ISSUE TITLE
Feature: Alert component

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/min-ui#16]
# Complete Alert component

Feature: Complete Alert component

## Complete alert component with 2 or 3 variants

This Feature will add a new alert component to the docs page.

## Alert tasks (Complete in order)

- [x] Task: Create basic alert component
- [x] Task: Create a filled alert component with all styles eg. warning, success
- [x] Task: create an alert component with only colored outlines.
- [x] Added close button to all alert component
- [x] Add code blocks
- [x] Add usage for alert button in docs
