### ISSUE TITLE
Feature: Button component

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/min-ui#17]
# Complete Button component

Feature: Complete Button component

## Complete Button component with mentioned variants

This Feature will add a new button component to the docs page.

## Button tasks (Complete in order)

- [x] Task: Create basic button component
- [x] Task: Create a button component (style filled colors) with all styles eg. warning, success
- [x] Task: Create a button component (style outlined colors) with all styles eg. warning, success
- [x] Added button component with icon
- [x] Add code snippets for the buttons
- [x] Add documentation page for buttons
- [x] Add button page link to all other pages.
