### ISSUE TITLE
Feature: Card component

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/min-ui#24]
# Completed card component

Feature: Card component

## Epic Description

This Feature will add acard components with all the variants

## List of Tasks (Complete in order)

- [x] #41
- [x] Cards with dismiss
- [x] Cards with text overlay
- [x] Text only cards
- [x] Vertical/Horizontal cards
- [x] Cards with shadow
