### ISSUE TITLE
Feature: Image and Input 

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/min-ui#25]
# Complete Image and input component

Feature: Image and Input component

## Epic Description

This Feature will add Image and Input component to the component library, and completes all P0 component.

### Image component
- [x] Add Image component with different shapes
- [x] Add responsive images
- [x] Add rounded image component 

### Input component 
- [x] Add default input component
- [x] Add input component for warning
- [x] Add input component for error
- [x] Add input component for success
