### ISSUE TITLE
Feature: Modal

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/min-ui#29]
# Complete Modal component

Feature: Modal component

## Epic Description

This Feature will add modal component and all its variants in the component library

## List of Tasks (Complete in order)

- [x] Simple alert modal with ok and cancel
- [x] Modal with stacked options
- [x] Modal with list of options
- [x] Modal with selection option
