### ISSUE TITLE
Site Enhancement

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/min-ui#33]
# Complete site enhancement changes

Feature: Site enhancement

## Epic Description

This Feature will add the remaining doc's info for the component library.

## List of Tasks (Complete in order)

- [x] Add Introduction
- [x] Add Usage info
- [x] Add color pallet, main colors used for the site.
- [x] Add typography info
