### ISSUE TITLE
Feature: Avatar components

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/min-ui#8]
# Completed avatars components

Feature Aler component

## Epic Description

This feature will add a list of avatars and badge components on the docs page. Listed with the specific heading

## Avatar tasks:

- [x] Task : Complete profile avtar
- [x] Task : Comlete profile avatar with different sizes
- [x] Task : Profile Avatar with status online/offline
- [x] Task : Profile avatar with different shapes
